# App Engine 앱의 런타임 환경을 설정합니다.
runtime: python312

# 앱 인스턴스의 성능 등급을 설정합니다. F1은 가장 기본적인 등급입니다.
instance_class: F1

# 앱을 시작하는 명령어입니다. gevent 워커를 사용하고 타임아웃을 비활성화합니다.
entrypoint: gunicorn --worker-class gevent -w 1 --timeout 0 run:app

# 앱에서 사용할 환경 변수를 설정합니다.
env_variables:
  # 여기에 본인의 OpenAI API 키를 붙여넣으세요.
  OPENAI_API_KEY: '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'
  
  # -- Cloud SQL 데이터베이스 연결 정보 --
  # PostgreSQL의 기본 사용자 이름입니다.
  DB_USER: 'postgres'
  
  # Cloud SQL 인스턴스 생성 시 설정한 비밀번호를 여기에 입력하세요.
  DB_PASS: 'hong1357900@'
  
  # PostgreSQL의 기본 데이터베이스 이름입니다.
  DB_NAME: 'postgres'
  
  # Google Cloud SQL 인스턴스 페이지에서 복사한 '인스턴스 연결 이름'을 여기에 붙여넣으세요.
  # 예: realtime-meeting-app-465901:asia-northeast3:meeting-db
  INSTANCE_CONNECTION_NAME: 'realtime-meeting-app-465901:us-central1:meeting-db'

# URL 요청을 처리하는 방법을 정의합니다.
handlers:
# /static URL로 들어오는 요청은 app/static 폴더의 정적 파일로 처리합니다.
- url: /static
  static_dir: app/static
  
# 그 외의 모든 URL 요청은 앱의 코드로 전달하여 처리합니다.
- url: /.*
  script: auto