runtime: python311
instance_class: F1

entrypoint: python3 run.py

env_variables:
  INSTANCE_CONNECTION_NAME: "realtime-meeting-app-465901:asia-northeast3:meeting-db"
  DB_USER: "postgres"
  DB_PASS: "1234"
  DB_NAME: "postgres"
  OPENAI_API_KEY_SECRET_NAME: "openai-api-key"

handlers:
- url: /static
  static_dir: app/static

- url: /.*
  script: auto