runtime: python312
instance_class: F1
entrypoint: gunicorn --worker-class gevent -w 1 --timeout 0 run:app

env_variables:
  # (수정됨) OpenAI API 키를 직접 넣는 대신, Secret Manager의 비밀 정보 이름을 지정합니다.
  OPENAI_API_KEY_SECRET_NAME: 'openai-api-key'
  
  # -- Cloud SQL 데이터베이스 연결 정보 --
  DB_USER: 'postgres'
  DB_PASS: '1234' # 이 부분은 그대로 둡니다.
  DB_NAME: 'postgres'
  INSTANCE_CONNECTION_NAME: 'realtime-meeting-app-465901:us-central1:meeting-db' # 이 부분은 그대로 둡니다.

network:
  session_affinity: true

handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: auto
